# Generated by Django 4.2.1 on 2023-05-22 18:46

import app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accomplishment',
            fields=[
                ('accomplishment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('progress_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2012), django.core.validators.MaxValueValidator(2050)])),
                ('journey', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='slack',
            fields=[
                ('slack_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('tech_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='projects', validators=[app.models.validate_image_project])),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('code_link', models.URLField(default='https://github.com')),
                ('project_link', models.URLField(default='#')),
                ('slacks', models.ManyToManyField(to='app.slack')),
            ],
        ),
    ]
