# Generated by Django 4.2.1 on 2023-05-24 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_project_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='tech',
            name='icon_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
