# Generated by Django 4.2.1 on 2023-05-29 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tech_icon_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tech',
            name='icon_name',
        ),
        migrations.AddField(
            model_name='tech',
            name='icon',
            field=models.ImageField(blank=True, upload_to='tech_icons'),
        ),
    ]
